Repository kyma-project/kyma-dashboard, pull requests merged in 2022-12, with the labels that each got.

#25 Update APIRules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/gateway/apirules.yaml
Labels: lgtm, size/S

#26 update functions
  extensions/serverless/functions.yaml
Labels: lgtm, size/XS

#27 Fix actions in general for list view
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#28 bring back original Subscriptions, enable creating on Functions view
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/serverless/functions.yaml
Labels: kind/bug, lgtm, size/S

#29 DesinationRules + ExtensibilityUI
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/istio/destination-rules.yaml
Labels: lgtm, size/XL

#30 bump commit version
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#31 update functions to include function templates on language change
  extensions/serverless/functions.yaml
Labels: lgtm, size/M

#32 fix reload vars on yaml and preset change
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#33 Use luigiless busola on dev
  environments/dev/env.sh
Labels: lgtm

#35 adjust dockers and configs to luigiless
  Dockerfile.local
  Dockerfile.web
  environments/dev/config.yaml
  environments/dev/env.sh
Labels: lgtm, size/M

#36 bump dev with nav fixes
  environments/dev/env.sh
Labels: lgtm, size/XS

#37 Bump dev with styling fix
  environments/dev/env.sh
Labels: lgtm, size/XS

#38 DEV push
  environments/dev/env.sh
Labels: lgtm, size/XS

#39 dev push
  environments/dev/env.sh
Labels: lgtm, size/XS

#40 bump dev
  environments/dev/env.sh
Labels: lgtm, size/XS

#41 bump stage
  environments/stage/env.sh
Labels: lgtm, size/XS

#42 Bump dev and stage images with extensions fix
  environments/dev/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS

#43 bump prod and adjust config
  environments/prod/config.yaml
  environments/prod/env.sh
Labels: lgtm, size/S

#46 bump environments to fix kubeconfigID feature
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#47 Update Dockerfile.local
  Dockerfile.local
Labels: lgtm, size/XS

#48 Update Dockerfile.local
  Dockerfile.local
Labels: lgtm, size/XS

#50 flags-in-children, refreshing-oidc and gardener login
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/stage/config.yaml
  environments/stage/env.sh
  extensions/gateway/apirules.yaml
  extensions/istio/authorization-policies.yaml
  extensions/istio/gateways.yaml
  extensions/istio/service-entries.yaml
  extensions/istio/sidecars.yaml
  extensions/istio/virtual-services.yaml
Labels: lgtm, size/L

#52 bump dev/stage/prod, fix lint
  .prettierignore
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/istio/destination-rules.yaml
  package.json
Labels: lgtm, size/S
