Repository kyma-project/kyma-dashboard, pull requests merged in 2022-11, with the labels that each got.

#1 Kyma Dashboard PoC
  .gitignore
  Dockerfile.backend
  Dockerfile.extensions
  Dockerfile.local
  Dockerfile.web
  Makefile
  docs/deployment.md
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/dev/extensions.json
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/prod/extensions.json
  environments/stage/config.yaml
  environments/stage/env.sh
  environments/stage/extensions.json
  extensions/applicationconnector/applications.yaml
  extensions/istio/authorization-policies.yaml
  extensions/istio/destination-rules.yaml
  extensions/istio/gateways.yaml
  extensions/istio/service-entries.yaml
  extensions/istio/sidecars.yaml
  extensions/istio/virtual-services.yaml
  extensions/serverless/functions.yaml
  gulpfile.js
  package-lock.json
  package.json
Labels: lgtm, size/XXL, area/documentation

#2 Update CODEOWNERS with hasselhoffs
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: lgtm, size/L

#3 Test gh actions
  .github/workflows/update_dev.yml
Labels: lgtm, size/M, area/ci

#4 Change the workflow schedule
  .github/workflows/update_dev.yml
Labels: lgtm, size/XS, area/ci

#5 Test gh actions
  .github/workflows/update_dev.yml
Labels: lgtm, size/XS, area/ci

#7 Update gateways, add subscriptions, change extensions,json
  environments/dev/extensions.json
  extensions/configuration/subscriptions.yaml
  extensions/istio/gateways.yaml
Labels: lgtm, size/L

#6 Bump stage and prod, add linter
  .github/ISSUE_TEMPLATE/decision-record.md
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .github/ISSUE_TEMPLATE/new-sig-or-wg-proposal.md
  .github/ISSUE_TEMPLATE/security-vulnerability.md
  .github/pull-request-template.md
  .prettierrc
  CONTRIBUTING.md
  NOTICE.md
  docs/deployment.md
  environments/dev/config.yaml
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/prod/extensions.json
  environments/stage/config.yaml
  environments/stage/env.sh
  environments/stage/extensions.json
  gulpfile.js
  package-lock.json
  package.json
Labels: lgtm, size/XXL, area/ci, area/documentation

#9 Push :latest image on prod
  Makefile
Labels: lgtm, size/S

#12 feat: bump prod to access new Functions views
  environments/prod/env.sh
Labels: lgtm, size/XS

#15 Stage: Fix PATCH request on edit
  environments/stage/env.sh
Labels: lgtm, size/XS

#16 Updating the KUBECONFIG_ID feature for local Docker
  Dockerfile.local
Labels: lgtm, size/XS

#14 Add Apirules
  environments/dev/env.sh
  environments/dev/extensions.json
  extensions/gateway/apirules.yaml
  extensions/serverless/functions.yaml
Labels: lgtm, size/L

#18 Add api rules configuration on stage and prod
  environments/prod/env.sh
  environments/prod/extensions.json
  environments/stage/env.sh
  environments/stage/extensions.json
Labels: lgtm, size/S

#20 Move apps to extensibility adjustments
  extensions/applicationconnector/applications.yaml
Labels: lgtm, size/L

#21 Update apirules - followup
  extensions/gateway/apirules.yaml
Labels: lgtm, size/M

#22 Update dev, stage and prod with latest ApiRules
  environments/dev/env.sh
  environments/dev/extensions.json
  environments/prod/env.sh
  environments/prod/extensions.json
  environments/stage/env.sh
  environments/stage/extensions.json
Labels: lgtm, size/S

#23 adding the kyma specific extensions
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/kyma/kyma.yaml
  extensions/kyma/moduleTemplate.yaml
Labels: lgtm, size/L

#24 adding logpipeline
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
Labels: lgtm, size/S
