Repository kyma-project/kyma-dashboard, pull requests merged in 2023-08, with the labels that each got.

#205 fix for modules in kyma resource
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS

#206 Fix/modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/S

#207 Update UI for API Rule with `introspection_url` and `introspection_request_headers`
  extensions/gateway/apirules.yaml
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/L

#209 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
  extensions/discovery-and-network/services.yaml
  extensions/gateway/apirules.yaml
  extensions/istio/authorization-policies.yaml
  extensions/istio/destination-rules.yaml
  extensions/istio/gateways.yaml
  extensions/istio/service-entries.yaml
  extensions/istio/virtual-services.yaml
  tests/tests/namespace/test-virtual-services.spec.js
Labels: lgtm, size/S

#208 move from nkyma to k3d with modular kyma
  tests/cypress.config.js
  tests/scripts/kyma-dashboard-integration.sh
  tests/support/login-commands.js
  tests/tests/cluster/test-modules-wizard.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-smoke-service-management.spec.js
Labels: lgtm, size/L

#218 Bumps
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
  tests/config.js
  tests/support/check-extension.js
  tests/support/commands.js
  tests/support/exceptions.js
  tests/support/helpers.js
  tests/support/navigate-to.js
  tests/support/views/api-rules-view.js
  tests/support/views/functions-view.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/a-run-before.spec.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-kyma.spec.js
  tests/tests/namespace/test-module-templates.spec.js
  tests/tests/namespace/z-run-after.spec.js
Labels: lgtm, size/M

#221 use kyma main instead of latest on CI
  tests/scripts/kyma-dashboard-integration.sh
Labels: lgtm, size/XS

#220 Adds timeout property to APIRule UI extension
  extensions/gateway/apirules.yaml
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/L

#222 fix: service instances and bidings language
  extensions/service-management/servicebindings.yaml
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/XS
