Repository kyma-project/kyma-dashboard, pull requests merged in 2023-03, with the labels that each got.

#128 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#100 Ext Subscriptions
  extensions/configuration/subscriptions.yaml
  tests/cypress.json
  tests/tests/namespace/test-check-extensions.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
Labels: lgtm, size/L

#129 remove Lyczeq and add valentin and cleanup mess
  CODEOWNERS
  OWNERS_ALIASES
Labels: lgtm, size/S

#130 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#134 fix visibility for required_scope
  extensions/gateway/apirules.yaml
Labels: do-not-merge/hold, lgtm, size/XS

#135 bumps with upload YAML
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#138 HPAs follow up
  extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
  tests/tests/namespace/test-hpa.spec.js
Labels: lgtm, size/L

#139 Add injections for kyma modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/M

#140 HPAs fix currentMetrics in detailsView
  extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
Labels: lgtm, size/S
