Repository kyma-project/kyma-dashboard, pull requests merged in 2023-04, with the labels that each got.

#143 updated to latest version and add global namespace option
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS

#126 Deprecate nodejs14, introduce nodejs18 runtime
  extensions/serverless/functions.yaml
Labels: lgtm, size/S

#146 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#147 fix configs
  environments/dev/config.yaml
  environments/prod/config.yaml
  environments/stage/config.yaml
  extensions/serverless/functions.yaml
Labels: lgtm, size/XS

#153 change gcr to europe-docker and resource validation
  Dockerfile.backend
  Dockerfile.local
  Dockerfile.web
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
Labels: lgtm, size/M

#150 Make it possible for adding statics as defaults on dev / stage and prod
  .gitignore
  Dockerfile.extensions
  Dockerfile.local
  Dockerfile.web
  environments/dev/env.sh
  environments/dev/statics.json
  environments/prod/env.sh
  environments/prod/statics.json
  environments/stage/env.sh
  environments/stage/statics.json
  extensions/statics/kibana-links.yaml
  gulpfile.js
  package.json
Labels: lgtm, size/L
