Repository kyma-project/kyma-dashboard, pull requests merged in 2023-01, with the labels that each got.

#61 remove Daria and Piotr as CODEOWNERS :sadcat:
  .prettierignore
  CODEOWNERS
Labels: lgtm, size/XS

#56 Tests
  .gitignore
  .prettierignore
  tests/README.md
  tests/config.js
  tests/cypress.json
  tests/fixtures/in-cluster-eventing-publisher-dependencies.json
  tests/fixtures/in-cluster-eventing-publisher.js
  tests/fixtures/in-cluster-eventing-receiver-dependencies.json
  tests/fixtures/in-cluster-eventing-receiver.js
  tests/fixtures/orders-function-dependencies.json
  tests/package-lock.json
  tests/package.json
  tests/plugins/index.js
  tests/support/commands.js
  tests/support/exceptions.js
  tests/support/helpers.js
  tests/support/index.js
  tests/support/inspect-list.js
  tests/support/loadFile.js
  tests/support/login-commands.js
  tests/support/mockConfig.js
  tests/support/navigate-to.js
  tests/support/paste-to-monaco.js
  tests/support/views/api-rules-view.js
  tests/support/views/functions-view.js
  tests/tests/cluster/run-after.spec.js
  tests/tests/cluster/run-before.spec.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/run-after.spec.js
  tests/tests/namespace/run-before.spec.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-in-cluster-eventing.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: lgtm, size/XXL

#63 Dev push
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#64 add missing description to apps
  extensions/applicationconnector/applications.yaml
Labels: lgtm, size/XS

#67 Fix configuration of accessStrategies
  environments/dev/env.sh
  extensions/gateway/apirules.yaml
  tests/fixtures/apirules-config-jwt.yaml
  tests/fixtures/apirules-config-read.yaml
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/M

#69 Bump stage and prod images with fixed api rules
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS

#70 fix sidecars
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/istio/sidecars.yaml
Labels: lgtm, size/S

#72 Bump api rules yaml and busola images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/gateway/apirules.yaml
  tests/fixtures/apirules-config-jwt.yaml
  tests/fixtures/apirules-config-read.yaml
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/L

#73 Dns entries
  environments/dev/env.sh
  extensions/configuration/dns-entries.yaml
  tests/cypress.json
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
Labels: lgtm, size/L

#76 bump images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  package.json
Labels: lgtm, size/S

#79 Issuers
  environments/dev/env.sh
  extensions/configuration/issuers.yaml
  tests/cypress.json
  tests/support/navigate-to.js
  tests/tests/namespace/test-api-rules.spec.js
  tests/tests/namespace/test-issuers.spec.js
Labels: lgtm, size/L

#84 enable istio in configs
  environments/dev/config.yaml
  environments/prod/config.yaml
  environments/stage/config.yaml
Labels: lgtm, size/XS

#86 feat: update service accounts to k8s 1.24
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#88 Update kyma.yaml
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS

#89 bump
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#91 Fix dockerfile
  Dockerfile.local
Labels: lgtm, size/XS

#92 fix dockerfile
  Dockerfile.local
Labels: lgtm, size/XS

#93 fix: dockerfile - probably I know what I'm doing
  Dockerfile.local
Labels: lgtm, size/XS

#95 disable GARDENER_LOGIN on dev
  environments/dev/config.yaml
Labels: lgtm, size/M

#96 Move hidden namespaces to kyma-dashboard
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
Labels: lgtm, size/M

#87 Configmap for ServiceInstances
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/L

#85 Configmap for ServiceBindings
  extensions/service-management/servicebindings.yaml
Labels: lgtm, size/L

#90 smoke tests for stage and prod
  .gitignore
  tests/README.md
  tests/cypress-smoke.json
  tests/package.json
  tests/support/check-extension.js
  tests/support/helpers.js
  tests/support/index.js
  tests/tests/cluster/test-check-extensions.spec.js
  tests/tests/namespace/test-check-extensions.spec.js
Labels: lgtm, size/L

#97 fix: visibility for selectors
  extensions/istio/authorization-policies.yaml
  extensions/istio/gateways.yaml
  extensions/istio/sidecars.yaml
Labels: lgtm, size/S

#74 configmap for certificates
  extensions/configuration/certificates.yaml
  tests/cypress.json
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-check-extensions.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
Labels: lgtm, size/L

#99 feat: add ServiceInstance and ServiceBindings smoke tests
  tests/cypress-smoke.json
  tests/fixtures/examples/service-binding-mock-crd.yaml
  tests/fixtures/examples/service-instance-mock-crd.yaml
  tests/tests/namespace/test-smoke-service-management.spec.js
Labels: lgtm, size/M

#102 bump sidecars version
  extensions/istio/sidecars.yaml
Labels: lgtm, size/XS
