Repository kyma-project/kyma-dashboard, pull requests merged in 2023-05, with the labels that each got.

#156 fix first time user experience
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS

#155 Change Subscription version to v1alpha2 in Serverless extension
  extensions/serverless/functions.yaml
Labels: lgtm, size/XS

#154 adjust makefile to ar
  Makefile
Labels: lgtm, size/S

#157 Display beta alert when corresponding module template has label "oper…
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#158 fix docker tags
  Makefile
Labels: lgtm, size/XS

#159 update version of module template
  extensions/kyma/kyma.yaml
  extensions/kyma/moduleTemplate.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/XS

#148 Fix Required Validation
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/istio/gateways.yaml
  tests/cypress.json
  tests/support/exceptions.js
Labels: lgtm, size/L

#162 Bump dev, stage and prod with upgraded patch
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#165 add enum for kyma channel
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/XS

#168 Improving the first time user experience for kyma modules
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#164 add defaults for first time UX with modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/S

#173 bump with change of hidden namespace flag
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#174 improve moduleTemplates and Kyma views, disableCreate and Edit for modules
  extensions/kyma/kyma.yaml
  extensions/kyma/moduleTemplate.yaml
Labels: lgtm, size/M

#175 removing defaults
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/XS

#176 bring back create and edit for kyma-modules
  extensions/kyma/moduleTemplate.yaml
Labels: lgtm, size/S

#177 disableCreate and Edit for Module Templates
  extensions/kyma/moduleTemplate.yaml
Labels: lgtm, size/S

#178 bumps, defaults for wizard and remove nodes
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#179 Add docs link on edit and in wizard
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#182 adjust enum function to allow only to choose option once
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/S

#183 Add version to module template details and list, add to edit and wizard
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
  extensions/kyma/moduleTemplate.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#184 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#185 Show version in channel not name
  extensions/kyma/kyma.yaml
  extensions/wizards/module-wizard.yaml
Labels: lgtm, size/M

#186 move serverless to link and remove unnecesary files
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/serverless/functions.yaml
  tests/tests/namespace/test-in-cluster-eventing.spec.js
Labels: lgtm, size/XL
