Repository kyma-project/kyma-dashboard, pull requests merged in 2023-12, with the labels that each got.

#249 remove observability
  environments/dev/config.yaml
  environments/prod/config.yaml
  environments/stage/config.yaml
  tests/scripts/kyma-dashboard-integration.sh
Labels: lgtm, size/S, cla: yes

#250 Bump busola versions
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#251 bumps node 20 and prometheus removal
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/package-lock.json
  tests/package.json
Labels: lgtm, size/XL, cla: yes

#252 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#253 add chriskari as a codeowner
  CODEOWNERS
  OWNERS_ALIASES
Labels: lgtm, size/XS, cla: yes

#254 Bump busola on dev with snow
  .gitignore
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#255 Bump busola
  environments/dev/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes
