Repository kyma-project/kyma-dashboard, pull requests merged in 2023-02, with the labels that each got.

#103 fix: change parameters widget to CodeEditor in ServiceBindings & ServiceInstances
  extensions/service-management/servicebindings.yaml
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/XS

#105 feat: enable service management section
  environments/dev/env.sh
  environments/dev/extensions.json
  environments/prod/env.sh
  environments/prod/extensions.json
  environments/stage/env.sh
  environments/stage/extensions.json
Labels: lgtm, size/S

#106 fix: negative highlight for CreateFailed status
  extensions/service-management/servicebindings.yaml
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/S

#107 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/serverless/functions.yaml
Labels: lgtm, size/S

#110 bump without trigger changes and remove oauth2
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/serverless/functions.yaml
  extensions/temp/oauth2.yaml
  tests/cypress.json
Labels: lgtm, size/S

#109 fix functions
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/configuration/oauth2.yaml
  extensions/serverless/functions.yaml
  tests/cypress.json
  tests/support/views/functions-view.js
Labels: lgtm, size/M

#112 Add translations for enums for destination rules and new multi-checkb…
  extensions/gateway/apirules.yaml
  extensions/istio/destination-rules.yaml
  tests/support/views/api-rules-view.js
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/M

#104 feat: modify Functions extension to the requirements
  extensions/serverless/functions.yaml
Labels: lgtm, size/M

#113 add trigger for sourceType in functions
  extensions/serverless/functions.yaml
Labels: lgtm, size/S

#114 feat: bump environments
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#117 remove workaround after kyma-cli release
  Dockerfile.local
Labels: lgtm, size/XS

#116 Prepare simple readme file with contribution rules
  CONTRIBUTING.md
  README.md
Labels: lgtm, size/M

#118 bump dev/stage/prod
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#119 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#120 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#122 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#123 fix related gateways in api-rules
  extensions/gateway/apirules.yaml
Labels: lgtm, size/S
