Repository kyma-project/kyma-dashboard, pull requests merged in 2023-09, with the labels that each got.

#223 remove enum for target adress
  extensions/configuration/dns-entries.yaml
  tests/tests/namespace/test-dns-entries.spec.js
Labels: lgtm, size/XS

#225 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S

#224 Kyma Resource adapt when user adds and remove module
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S

#228 fix links for log parsers and log pipelines
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  tests/scripts/kyma-dashboard-integration.sh
Labels: lgtm, size/S

#229 add telemetry tracepipeline config, remove logparser
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  tests/tests/cluster/test-check-extensions.spec.js
Labels: lgtm, size/S

#227 Notification about OAuth2Clients deprecation
  extensions/configuration/oauth2.yaml
  tests/tests/namespace/test-oauth2.spec.js
Labels: lgtm, size/M, area/api-gateway

#230 bump
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S
