Repository kyma-project/kyma-dashboard, pull requests merged in 2023-06, with the labels that each got.

#187 Add link for documentation on the cluster details injection for kyma
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S

#188 move subscription extension to link
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/configuration/subscriptions.yaml
Labels: lgtm, size/L

#190 Enable extensibility wizard and injections on prod
  environments/prod/config.yaml
  extensions/configuration/oauth2.yaml
Labels: lgtm, size/XS
