Repository kyma-project/kyma-dashboard, pull requests merged in 2024-06, with the labels that each got.

#297 feat: bring back hpa and dns entries tests
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/cypress.config.js
Labels: lgtm, size/S, cla: yes

#301 fix: busola bump
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes

#302 fix: custom urlPath for extensibility
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#303 fix: urlPath
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#308 feat: add kyma-dashboard dev build workflow
  .github/workflows/kyma-dashboard-dev-build.yml
  Dockerfile.backend
  Dockerfile.local
  Dockerfile.web
Labels: lgtm, size/M, area/ci, cla: yes

#309 fix: needs build image for dev build, remove update dev
  .github/workflows/kyma-dashboard-dev-build.yml
  .github/workflows/update_dev.yml
Labels: lgtm, size/M, area/ci, cla: yes

#310 fix: change build-image to build-extensions
  .github/workflows/kyma-dashboard-dev-build.yml
Labels: lgtm, size/XS, area/ci, cla: yes

#311 feat: add checkout on kyma-dashboard
  .github/workflows/kyma-dashboard-dev-build.yml
Labels: lgtm, size/XS, area/ci, cla: yes

#312 fix: add chmod
  .github/workflows/kyma-dashboard-dev-build.yml
Labels: lgtm, size/XS, area/ci, cla: yes

#304 feat: UX adjustments - Modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S, cla: yes

#316 fix: modeSelector for form
  environments/dev/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes

#315 removed AI banner
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S, cla: yes

#321 fix: fix gha build, remove build-extensions, add test-image
  .github/workflows/kyma-dashboard-dev-build.yml
Labels: lgtm, size/M, area/ci, cla: yes

#319 feat: add comand for building extensions
  .githooks/pre-commit.d/01-prepare-extensibility.sh
  package.json
Labels: lgtm, size/S, cla: yes

#317 feat: add dockerfiles for image builder and adjust dev build on gha
  .github/workflows/kyma-dashboard-dev-build.yml
  Dockerfile.local.builder
  Dockerfile.web.builder
Labels: lgtm, size/M, area/ci, cla: yes

#327 fix tags for dev build
  .github/workflows/kyma-dashboard-dev-build.yml
Labels: lgtm, size/S, area/ci, cla: yes

#330 Bump prod image
  environments/prod/env.sh
Labels: lgtm, size/XS, cla: yes

#331 feat: modules baner on cluster details
  environments/dev/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes

#324 feat: gha for checking extensibility changes
  .github/scripts/check-extensibility.sh
  .github/workflows/check-extensibility.yml
Labels: lgtm, size/M, area/ci, cla: yes

#336 feat: final version of the script and workflow for checking extensibility
  .github/scripts/check-extensibility.sh
  .github/workflows/check-extensibility.yml
Labels: lgtm, size/M, area/ci, cla: yes

#328 fix: move env in dockerfiles and fix outputs
  .github/workflows/kyma-dashboard-dev-build.yml
  Dockerfile.backend
  Dockerfile.local.builder
  Dockerfile.web.builder
Labels: lgtm, size/S, area/ci, cla: yes

#337 feat: OSS Rules
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: lgtm, size/L, cla: yes

#340 feat: add action for cypress tests
  .github/scripts/setup-busola.sh
  .github/scripts/setup-kyma.sh
  .github/workflows/pull-intergation-tests.yml
  environments/dev/dist/extensions.yaml
  environments/dev/extensions.json
  environments/prod/dist/extensions.yaml
  environments/prod/extensions.json
  environments/stage/dist/extensions.yaml
  environments/stage/extensions.json
Labels: lgtm, size/XXL, area/ci, cla: yes

#342 feat: busola bumps
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/prod/env.sh
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  tests/support/create-edit-support.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/a-run-before.spec.js
  tests/tests/namespace/test-kyma.spec.js
Labels: lgtm, size/M, cla: yes
