Repository kyma-project/kyma-dashboard, pull requests merged in 2024-05, with the labels that each got.

#290 fix: kyma injections isSapUser
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS, cla: yes

#285 feat: kyma modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S, cla: yes

#291 Deprecate kyma provision k3d command
  tests/scripts/kyma-dashboard-integration.sh
Labels: lgtm, size/XS, cla: yes

#292 bump UI5 and testing packages
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/package-lock.json
  tests/package.json
  tests/tests/namespace/a-run-before.spec.js
Labels: lgtm, size/M, cla: yes

#293 feat: add modules, card view
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#294 fix: no modules in status
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#295 Unify Kyma CR description in Kyma dasborad
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS, cla: yes

#296 feat, fix: UX adjustements, injections, delete on edit, schema in add modules, hide create secret in SA
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/cypress.config.js
  tests/package-lock.json
  tests/package.json
  tests/tests/namespace/test-hpa.spec.js
Labels: lgtm, size/S, cla: yes

#299 fix: revert prod bump
  environments/prod/env.sh
Labels: lgtm, size/XS, cla: yes

#300 feat: remove labels from list
  environments/dev/env.sh
  tests/tests/namespace/test-dns-providers.spec.js
Labels: lgtm, size/XS, cla: yes
