Repository kyma-project/kyma-dashboard, pull requests merged in 2024-07, with the labels that each got.

#341 feat: Add resource graph and status information to HPA
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/prod/env.sh
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  extensions/discovery-and-network/horizontal-pod-autoscalers.yaml
Labels: lgtm, size/L, cla: yes

#344 feat: change channel for the module, adjust deployments
  Dockerfile.local.builder
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#346 feat: add tests for Kyma Modules
  .github/scripts/setup-kyma.sh
  environments/dev/env.sh
  environments/stage/env.sh
  extensions/modules/api-gateway-regular.yaml
  extensions/modules/eventing-fast.yaml
  extensions/modules/eventing-regular.yaml
  tests/cypress.config.js
  tests/scripts/kyma-dashboard-integration.sh
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/XL, area/ci, cla: yes

#347 bump: bump busola with fix for modules
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/S, cla: yes

#348 Bump dev and stage
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/support/create-edit-support.js
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/S, cla: yes

#349 test: adjust kyma modules test
  .github/workflows/pull-smoke-test-prod.yml
  .github/workflows/pull-smoke-test-stage.yml
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/L, area/ci, cla: yes
