Repository kyma-project/kyma-dashboard, pull requests merged in 2024-01, with the labels that each got.

#265 bumps and remove snow from config
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#266 fix kyma modularization docs
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS, cla: yes

#267 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/cypress.config.js
  tests/support/commands.js
  tests/support/exceptions.js
  tests/tests/namespace/test-hpa.spec.js
  tests/tests/namespace/test-module-templates.spec.js
Labels: lgtm, size/M, cla: yes

#268 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#269 Remove module templates
  extensions/kyma/moduleTemplate.yaml
Labels: lgtm, size/M, cla: yes

#270 bumps with generate token fix
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  tests/support/login-commands.js
Labels: lgtm, size/S, cla: yes

#272 bump kyma version
  extensions/kyma/kyma.yaml
Labels: lgtm, size/XS, cla: yes
