Repository kyma-project/kyma-dashboard, pull requests merged in 2024-02, with the labels that each got.

#246 Remove API Gateway extension from kyma-dashboard
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/gateway/apirules.yaml
  tests/cypress.config.js
  tests/support/index.js
  tests/support/views/functions-view.js
  tests/tests/namespace/run-prepare-functions.spec.js
  tests/tests/namespace/test-api-rules.spec.js
Labels: lgtm, size/XXL, cla: yes

#273 modules promotion banner
  environments/dev/config.yaml
  environments/dev/env.sh
  environments/prod/config.yaml
  environments/prod/env.sh
  environments/stage/config.yaml
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
  tests/cypress-smoke.js
  tests/support/commands.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-hpa.spec.js
  tests/tests/namespace/test-oauth2.spec.js
Labels: lgtm, size/L, cla: yes

#274 bump
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#275 bumps
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#277 feat: change wizard to resourceButton
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
  tests/support/commands.js
  tests/support/inspect-list.js
  tests/support/login-commands.js
  tests/tests/cluster/test-applications.spec.js
  tests/tests/namespace/a-run-before.spec.js
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-certificates.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-dns-entries.spec.js
  tests/tests/namespace/test-dns-providers.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-hpa.spec.js
  tests/tests/namespace/test-issuers.spec.js
  tests/tests/namespace/test-kyma.spec.js
  tests/tests/namespace/test-oauth2.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-services.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
  tests/tests/namespace/z-run-after.spec.js
Labels: lgtm, size/L, cla: yes
