Repository kyma-project/kyma-dashboard, pull requests merged in 2024-04, with the labels that each got.

#282 fix: service instances, bindings and application docs links
  extensions/applicationconnector/applications.yaml
  extensions/service-management/servicebindings.yaml
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/S, cla: yes

#283 fix: edit CR, SAP Logo
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#287 feat: remove istio extensions and tests
  environments/dev/extensions.json
  environments/prod/extensions.json
  environments/stage/extensions.json
  extensions/istio/authorization-policies.yaml
  extensions/istio/destination-rules.yaml
  extensions/istio/gateways.yaml
  extensions/istio/service-entries.yaml
  extensions/istio/sidecars.yaml
  extensions/istio/virtual-services.yaml
  tests/cypress.config.js
  tests/scripts/kyma-dashboard-integration.sh
  tests/tests/namespace/test-authorization-policies.spec.js
  tests/tests/namespace/test-check-extensions.spec.js
  tests/tests/namespace/test-destination-rules.spec.js
  tests/tests/namespace/test-gateways.spec.js
  tests/tests/namespace/test-service-entries.spec.js
  tests/tests/namespace/test-sidecars.spec.js
  tests/tests/namespace/test-virtual-services.spec.js
Labels: lgtm, size/XXL, cla: yes

#288 add Oliwia as codeowner
  CODEOWNERS
  OWNERS_ALIASES
Labels: lgtm, size/XS, cla: yes

#286 feat: added AI FeatureCard banner
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/M, cla: yes

#289 fix: kyma injections
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
  extensions/kyma/kyma.yaml
Labels: lgtm, size/S, cla: yes
