Repository kyma-project/kyma-dashboard, pull requests merged in 2024-08, with the labels that each got.

#350 feat: adjust edit and add modules tests
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  tests/support/create-edit-support.js
  tests/tests/cluster/test-check-extensions.spec.js
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/L, cla: yes

#352 feat: adjust extensibility forms to handle the permissions model
  environments/dev/dist/extensions.yaml
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  extensions/configuration/certificates.yaml
  extensions/configuration/dns-providers.yaml
  extensions/configuration/oauth2.yaml
  extensions/service-management/servicebindings.yaml
Labels: lgtm, size/L, cla: yes

#351 test: delete module from details
  environments/dev/env.sh
  environments/stage/env.sh
  tests/support/commands.js
  tests/tests/cluster/test-kyma-modules.spec.js
Labels: lgtm, size/M, cla: yes

#353 feat: bump with extensibility nodes for statics
  environments/dev/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes

#357 fix: fix dependencies in builds
  .github/workflows/kyma-dashboard-dev-build.yml
  .github/workflows/kyma-dashboard-prod-build.yml
Labels: lgtm, size/XS, area/ci, cla: yes

#359 feat: bump prod with stage image
  environments/prod/env.sh
Labels: lgtm, size/XS, cla: yes

#360 feat: adjust certificates
  environments/dev/dist/extensions.yaml
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  extensions/configuration/certificates.yaml
Labels: lgtm, size/XL, cla: yes

#362 feat: add latest tag to builds
  .github/workflows/kyma-dashboard-dev-build.yml
  .github/workflows/kyma-dashboard-prod-build.yml
  .github/workflows/kyma-dashboard-stage-build.yml
Labels: lgtm, size/XS, area/ci, cla: yes

#363 feat: bump busola images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#364 feat: bump busola images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes

#365 feat: change nginx image, bump busola images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/XS, cla: yes

#367 Fix permission after changes in busola
  Dockerfile.web
  Dockerfile.web.builder
Labels: lgtm, size/S, cla: yes
