Repository kyma-project/kyma-dashboard, pull requests merged in 2024-09, with the labels that each got.

#368 chore: modify dockerfiles and adjust github workflows
  .github/workflows/kyma-dashboard-dev-build.yml
  .github/workflows/kyma-dashboard-prod-build.yml
  .github/workflows/kyma-dashboard-stage-build.yml
  Dockerfile.local
  Dockerfile.web
Labels: lgtm, size/M, area/ci, cla: yes

#366 feat: enhance issuers
  environments/dev/dist/extensions.yaml
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  extensions/configuration/issuers.yaml
Labels: lgtm, size/L, cla: yes

#370 docs: Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, size/XS, cla: yes

#369 chore: cleanup unused dockerfiles
  Dockerfile.local.builder
  Dockerfile.web.builder
  Makefile
  README.md
  docs/deployment.md
Labels: lgtm, size/M, area/documentation, cla: yes

#373 chore: Update codeowners
  CODEOWNERS
Labels: lgtm, size/XS, cla: yes

#371 feat: Enhance DNS Entries
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/prod/env.sh
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  extensions/configuration/certificates.yaml
  extensions/configuration/dns-entries.yaml
Labels: lgtm, size/L, cla: yes

#372 feat: enhance service bindings
  environments/dev/dist/extensions.yaml
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  extensions/service-management/servicebindings.yaml
Labels: lgtm, size/XL, cla: yes

#374 feat: enhance Service Instances
  environments/dev/dist/extensions.yaml
  environments/prod/dist/extensions.yaml
  environments/stage/dist/extensions.yaml
  extensions/service-management/serviceinstances.yaml
Labels: lgtm, size/XL, cla: yes

#376 feat: Enhance Services
  environments/dev/dist/extensions.yaml
  environments/dev/env.sh
  environments/prod/dist/extensions.yaml
  environments/prod/env.sh
  environments/stage/dist/extensions.yaml
  environments/stage/env.sh
  extensions/discovery-and-network/services.yaml
Labels: lgtm, size/XL, cla: yes

#377 feat: bump busola images
  environments/dev/env.sh
  environments/prod/env.sh
  environments/stage/env.sh
Labels: lgtm, size/S, cla: yes
